[package]
name = "Image-effects"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
base64 = "0.22.1"
image = "0.25.6"

[dependencies.web-sys]
version = "0.3.77"
features = ["console"]

